export {
  AppleECGAlgorithmVersion,
  BloodGlucoseMealTime,
  BodyTemperatureSensorLocation,
  CyclingFunctionalThresholdPowerTestType,
  DevicePlacementSide,
  HeartRateRecoveryTestType,
  HeartRateSensorLocation,
  PhysicalEffortEstimationType,
  SwimmingStrokeStyle,
  UserMotionContext,
  VO2MaxTestType,
  WaterSalinity,
  WorkoutSwimmingLocationType,
} from '../generated/healthkit.generated'
