name: Dev Client

on:
  pull_request_target:
  push:
    branches:
      - master
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run nitro-codegen
        working-directory: packages/react-native-healthkit
      
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Continuously Deploy
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          auto-submit-builds: true
          platform: ios
          working-directory: ./apps/example
          profile: development-appstore-connect
          branch: ${{ github.ref_name }}
          